/* DO NOT MODIFY BY HAND
 * Generated from: Platform.Legacy.CodeGen.Generators.ScopesGenerator
 * Generated At: 2025-05-27T16:13:58
 * Generated By: REDACTED
 * Generated On: REDACTED
 * DO NOT MODIFY BY HAND
*/

namespace Platform.Legacy.Common.Constants.Scopes;

/// <summary>
/// OpenID Scopes used for Identity Tokens
/// </summary>
public class OpenId
{
	/// <summary>
	/// The mandatory openid scope to elevate from OAuth2 to OIDC. Requires the 'sub' claim to be present.
	/// </summary>
	public const string OPENID = "openid";

	/// <summary>
	/// Scope to receive at a minimum 'name' but possibly including additional user profile details
	/// </summary>
	public const string PROFILE = "profile";

	/// <summary>
	/// Scope to receive the 'email' and 'email_verified' claims
	/// </summary>
	public const string EMAIL = "email";

	/// <summary>
	/// Scope to receive the 'phone_number' and 'phone_number_verified' claims
	/// </summary>
	public const string PHONE = "phone";

	/// <summary>
	/// Scope to request a refresh token is issued alongside an acces token
	/// </summary>
	public const string OFFLINE_ACCESS = "offline_access";

	/// <summary>
	/// All Possible Values
	/// </summary>
	public static readonly Dictionary<string, string> Values = new()
	{
		{
			"openid",
			"The mandatory openid scope to elevate from OAuth2 to OIDC. Requires the 'sub' claim to be present."
		},
		{ "profile", "Scope to receive at a minimum 'name' but possibly including additional user profile details" },
		{ "email", "Scope to receive the 'email' and 'email_verified' claims" },
		{ "phone", "Scope to receive the 'phone_number' and 'phone_number_verified' claims" },
		{ "offline_access", "Scope to request a refresh token is issued alongside an acces token" },
	};

	/// <summary>
	/// Value Groupings
	/// </summary>
	public static readonly Dictionary<string, List<string>> Groups = new();
}
