// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SESAggregator.Data;

#nullable disable

namespace SESAggregator.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230430044915_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SESAggregator.Data.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastFailureMessage")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastSendingAttemptAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("PermanentlyFailed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SendingApplication")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SuccessfullySent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ToName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tries")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Message");
                });
#pragma warning restore 612, 618
        }
    }
}
