using Microsoft.Extensions.DependencyInjection;
using Platform.Legacy.CodeGen.Generators;
using Platform.Legacy.CodeGen.Models;

const string CODEGEN_ROOT_MARKER = nameof(CODEGEN_ROOT_MARKER);
DirectoryInfo baseDirectory = new(Environment.CurrentDirectory);
bool foundMarker = false;
while (!foundMarker)
{
	foundMarker = baseDirectory.EnumerateFiles().Where(x => x.Name == CODEGEN_ROOT_MARKER).Any();
	if (foundMarker)
	{
		continue;
	}

	if (baseDirectory.Parent is null)
	{
		Console.Error.WriteLine("Failed to locate the root marker for codegen!");
		return -1;
	}

	baseDirectory = baseDirectory.Parent;
}

Console.WriteLine($"Root Marker found at: {baseDirectory.FullName}");

IServiceCollection serviceCollection = new ServiceCollection();

// Add Services here
IServiceProvider serviceProvider = serviceCollection.BuildServiceProvider();
using IServiceScope scope = serviceProvider.CreateScope();

List<Type> generatorTypes = [.. typeof(Program)
	.Assembly.GetTypes()
	.Where(x => x is { IsAbstract: false, IsInterface: false, } && x.IsAssignableTo(typeof(IGenerator))),];

List<CodeGeneratorResult> files = [];

bool hasErrors = false;
foreach (Type generatorType in generatorTypes)
{
	try
	{
		string[] fileComment =
		[
			"DO NOT MODIFY BY HAND",
			$"Generated from: {generatorType.FullName}",
			$"Generated At: {DateTime.Now:s}",
			$"Generated By: {Environment.UserName}",
			$"Generated On: {Environment.MachineName}",
			"DO NOT MODIFY BY HAND",
		];

		if (ActivatorUtilities.CreateInstance(provider: scope.ServiceProvider, instanceType: generatorType) is not IGenerator generator)
		{
			throw new InvalidOperationException($"Failed to activate an instance of type");
		}

		files.AddRange(await generator.Generate(fileComment));
	}
	catch (Exception ex)
	{
		Console.Error.WriteLine($"Failed to run generator {generatorType.FullName}: {ex.Message}");
		hasErrors = true;
	}
}
if (hasErrors)
{
	return -1;
}

bool dirty = false;
foreach (CodeGeneratorResult file in files)
{
	try
	{
		string path = Path.GetFullPath(Path.Combine(path1: baseDirectory.FullName, path2: file.OutputPath));
		File.WriteAllText(path: path, contents: file.Code);
		dirty = true;
		Console.WriteLine($"Wrote: \"{path}\"");
	}
	catch (Exception ex)
	{
		Console.Error.WriteLine($"Failed to write file \"{file.OutputPath}\": {ex.Message}");
		hasErrors = true;
	}
}

if (hasErrors)
{
	if (dirty)
	{
		Console.Error.WriteLine(
			"WARNING! Some Code files were written but an error occured that prevented writing all of the generated source. The output state is dirty!"
		);
	}
	return -1;
}

return 0;
