/* DO NOT MODIFY BY HAND
 * Generated from: Platform.Legacy.CodeGen.Generators.ScopesGenerator
 * Generated At: 2025-05-27T16:13:58
 * Generated By: REDACTED
 * Generated On: REDACTED
 * DO NOT MODIFY BY HAND
*/

namespace Platform.Legacy.Common.Constants.Scopes;

/// <summary>
/// Scopes to indicate with frontend modules should be visible
/// </summary>
public class Modules
{
	/// <summary>
	/// Access to all modules
	/// </summary>
	public const string MODULES_ALL = "modules:all";

	/// <summary>
	/// General-Availability modules that are active for everyone by default
	/// </summary>
	public const string MODULES_GA = "modules:ga";

	/// <summary>
	/// Modules that are in Public-Beta
	/// </summary>
	public const string MODULES_BETA = "modules:beta";

	/// <summary>
	/// Core modules that are needed for basic functionality, such as authentication and account
	/// </summary>
	public const string MODULES_CORE = "modules.core";

	/// <summary>
	/// Access to Assets
	/// </summary>
	public const string MODULES_ASSETS = "modules.assets";

	/// <summary>
	/// Access to the Timeclock
	/// </summary>
	public const string MODULES_TIMECLOCK = "modules.timeclock";

	/// <summary>
	/// Access to Log-It Issues
	/// </summary>
	public const string MODULES_ISSUES = "modules.issues";

	/// <summary>
	/// Access to Forms
	/// </summary>
	public const string MODULES_FORMS = "modules.forms";

	/// <summary>
	/// Access to Messaging
	/// </summary>
	public const string MODULES_MESSAGING = "modules.messaging";

	/// <summary>
	/// Access to Documents
	/// </summary>
	public const string MODULES_DOCUMENTS = "modules.documents";

	/// <summary>
	/// Access to Training
	/// </summary>
	public const string MODULES_TRAINING = "modules.training";

	/// <summary>
	/// Access to Billing
	/// </summary>
	public const string MODULES_BILLING = "modules.billing";

	/// <summary>
	/// Access to Reports
	/// </summary>
	public const string MODULES_REPORTS = "modules.reports";

	/// <summary>
	/// Access to the Store
	/// </summary>
	public const string MODULES_STORE = "modules.store";

	/// <summary>
	/// Access to Planners
	/// </summary>
	public const string MODULES_PLANNERS = "modules.planners";

	/// <summary>
	/// All Possible Values
	/// </summary>
	public static readonly Dictionary<string, string> Values = new()
	{
		{ "modules:all", "Access to all modules" },
		{ "modules:ga", "General-Availability modules that are active for everyone by default" },
		{ "modules:beta", "Modules that are in Public-Beta" },
		{ "modules.core", "Core modules that are needed for basic functionality, such as authentication and account" },
		{ "modules.assets", "Access to Assets" },
		{ "modules.timeclock", "Access to the Timeclock" },
		{ "modules.issues", "Access to Log-It Issues" },
		{ "modules.forms", "Access to Forms" },
		{ "modules.messaging", "Access to Messaging" },
		{ "modules.documents", "Access to Documents" },
		{ "modules.training", "Access to Training" },
		{ "modules.billing", "Access to Billing" },
		{ "modules.reports", "Access to Reports" },
		{ "modules.store", "Access to the Store" },
		{ "modules.planners", "Access to Planners" },
	};

	/// <summary>
	/// Value Groupings
	/// </summary>
	public static readonly Dictionary<string, List<string>> Groups = new()
	{
		{
			"modules:all",
			[
				"modules.core",
				"modules.assets",
				"modules.timeclock",
				"modules.issues",
				"modules.forms",
				"modules.messaging",
				"modules.documents",
				"modules.training",
				"modules.billing",
				"modules.reports",
				"modules.store",
				"modules.planners",
			]
		},
		{
			"modules:ga",
			[
				"modules.core",
				"modules.assets",
				"modules.timeclock",
				"modules.issues",
				"modules.forms",
				"modules.messaging",
				"modules.documents",
				"modules.training",
				"modules.billing",
				"modules.reports",
				"modules.store",
			]
		},
		{ "modules:beta", ["modules.planners",] },
	};
}
