/* DO NOT MODIFY BY HAND
 * Generated from: Platform.Legacy.CodeGen.Generators.RolesGenerator
 * Generated At: 2025-05-27T16:13:58
 * Generated By: REDACTED
 * Generated On: REDACTED
 * DO NOT MODIFY BY HAND
*/

namespace Platform.Legacy.Common.Constants.Scopes;

/// <summary>
/// Roles to define broad permissions boundaries
/// </summary>
public class Roles
{
	/// <summary>
	/// Basic role for organization employees
	/// </summary>
	public const string ROLES_ORG_EMPLOYEE = "roles.org.employee";

	/// <summary>
	/// Basic role for organization contractors
	/// </summary>
	public const string ROLES_ORG_CONTRACTOR = "roles.org.contractor";

	/// <summary>
	/// User within an organization that manages other users
	/// </summary>
	public const string ROLES_ORG_MANAGER = "roles.org.manager";

	/// <summary>
	/// User with access to HR PII systems
	/// </summary>
	public const string ROLES_ORG_HUMAN_RESOURCES = "roles.org.human_resources";

	/// <summary>
	/// User with access to billing / invoicing details
	/// </summary>
	public const string ROLES_ORG_BILLING = "roles.org.billing";

	/// <summary>
	/// User with access to payroll processing systems
	/// </summary>
	public const string ROLES_ORG_PAYROLL = "roles.org.payroll";

	/// <summary>
	/// User with full control of a company
	/// </summary>
	public const string ROLES_ORG_SUPER_ADMIN = "roles.org.super_admin";

	/// <summary>
	/// Sales Team
	/// </summary>
	public const string ROLES_SYS_SALES = "roles.sys.sales";

	/// <summary>
	/// Support Team
	/// </summary>
	public const string ROLES_SYS_SUPPORT = "roles.sys.support";

	/// <summary>
	/// Accounting team
	/// </summary>
	public const string ROLES_SYS_ACCOUNTING = "roles.sys.accounting";

	/// <summary>
	/// Development Team
	/// </summary>
	public const string ROLES_SYS_DEVELOPER = "roles.sys.developer";

	/// <summary>
	/// All Possible Values
	/// </summary>
	public static readonly Dictionary<string, string> Values = new()
	{
		{ "roles.org.employee", "Basic role for organization employees" },
		{ "roles.org.contractor", "Basic role for organization contractors" },
		{ "roles.org.manager", "User within an organization that manages other users" },
		{ "roles.org.human_resources", "User with access to HR PII systems" },
		{ "roles.org.billing", "User with access to billing / invoicing details" },
		{ "roles.org.payroll", "User with access to payroll processing systems" },
		{ "roles.org.super_admin", "User with full control of a company" },
		{ "roles.sys.sales", "Sales Team" },
		{ "roles.sys.support", "Support Team" },
		{ "roles.sys.accounting", "Accounting team" },
		{ "roles.sys.developer", "Development Team" },
	};

	/// <summary>
	/// Value Groupings
	/// </summary>
	public static readonly Dictionary<string, List<string>> Groups = new();
}
