using System.Security.Cryptography;

namespace CaptivePortal.Helpers
{
    public static class TemporaryPassword
    {
        public static string Generate()
        {
            using RandomNumberGenerator rng = RandomNumberGenerator.Create();
            byte[] int32Bytes = new byte[4];

            rng.GetBytes(int32Bytes, 0, 4);
            int adjective = Convert.ToInt32(BitConverter.ToUInt32(int32Bytes, 0) % Adjectives.Count);

            rng.GetBytes(int32Bytes, 0, 4);
            int animal = Convert.ToInt32(BitConverter.ToUInt32(int32Bytes, 0) % Animals.Count);

            rng.GetBytes(int32Bytes, 0, 4);
            int number = Convert.ToInt32((BitConverter.ToUInt32(int32Bytes, 0) % 90) + 10);

            return $"{Adjectives[adjective]}{Animals[animal]}{number}";
        }
        
        public static List<string> Adjectives = [
            "Glistening",
            "Dazzling",
            "Glowing",
            "Gleaming",
            "Twinkling",
            "Sparkling",
            "Glimmering",
            "Shimmering",
            "Glittering",
            "Brilliant",
            "Radiant",
            "Vibrant",
            "Vivid",
            "Tiny",
            "Miniature",
            "Miniscule",
            "Small",
            "Compact",
            "Minimal",
            "Lovely",
            "Charming",
            "Stunning",
            "Captivating",
            "Adorable",
            "Classy",
            "Elegant",
            "Sleek",
            "Dreadful",
            "Awful",
            "Ghastly",
            "Wicked",
            "Unsightly",
            "Shocking",
            "Roguish",
            "Crooked",
            "Sinister",
            "Wily",
            "Sly",
            "Crafty",
            "Foul",
            "Gloomy",
            "Shadowy",
            "Murky",
            "Shady",
            "Huge",
            "Large",
            "Vast",
            "Immense",
            "Gigantic",
            "Colossal",
            "Massive",
            "Sizeable",
            "Hefty",
            "Wonderful",
            "Delightful",
            "Fabulous",
            "Fantastic",
            "Marvelous",
            "Splendid",
            "Glorious",
            "Magnificent",
            "Superb",
            "Excellent",
            "Kind",
            "Friendly",
            "Personable",
            "Pleasant",
            "Agreeable",
            "Cordial",
            "Cherished",
            "Prized",
            "Esteemed",
            "Revered",
            "Adored",
            "Uppity",
            "Moral",
            "Virtuous",
            "Righteous",
            "Honest",
            "Noble",
            "Wholesome",
            "Pure",
            "Innocent",
            "Saintly",
            "Courteous",
            "Obedient",
            "Trustworthy",
            "Upstanding",
            "Upright",
            "Respectable",
            "Gallant",
            "Benevolent",
            "Terrific",
            "Superior",
            "Extraordinary",
            "Marvelous",
            "Super",
            "Exemplary",
            "Awesome",
            "Fascinating",
            "Inventive",
            "Innovating",
            "Produtive",
            "Expect"
        ];

        public static List<string> Animals = [
            "Elephant",
            "Alligator",
            "Crocodile",
            "Fox",
            "Bat",
            "Yak",
            "Bison",
            "Ferret",
            "Warbler",
            "Cheetah",
            "Turtle",
            "Tortoise",
            "Dolphin",
            "Frog",
            "Bear",
            "Hummingbird",
            "Jaguar",
            "Panther",
            "Lion",
            "Seal",
            "Narwhal",
            "Ocelot",
            "Orca",
            "Whale",
            "Penguin",
            "Hawk",
            "Eagle",
            "Gazelle",
            "Owl",
            "Otter",
            "Snake",
            "Tiger",
            "Badger",
            "Wolf",
            "Walrus",
            "Leapord",
            "Moose",
            "Elk",
            "Deer",
            "Coyote",
            "Parrot",
            "Gorilla",
            "Shark",
            "Vulture",
            "Trout",
            "Salmon",
            "Halibut",
            "Tuna",
            "Carp",
            "Shrimp",
            "Mackerel",
            "Anchovy",
            "Tilapia",
            "Herring",
            "Crow",
            "Raven",
            "Sparrow",
            "Starling",
            "Magpie",
            "Baboon",
            "Rhinoceros",
            "Zebra",
            "Giraffe",
            "Buffalo",
            "Antelope",
            "Hyena",
            "Flamingo",
            "Ostrich",
            "Kangaroo",
            "Horse",
            "Cow",
            "Sheep",
            "Anteater",
            "Panda",
            "Llama",
            "Camel",
            "Squid",
            "Squirrel",
            "Chipmunk",
            "Racoon"
        ];
    }
}
